### ISSUE TITLE
请问这个有旋转功能吗？

### ISSUE THREAD

**Issue by speedpursuer** [lincf0912/LFImagePickerController#1]
功能都很赞！如果能有左右90度旋转就更好了！

**Comment by speedpursuer** [comment]
可以参考这个，把旋转和裁剪功能整合到一起，就完美了！
https://github.com/TimOliver/TOCropViewController

**Comment by lincf0912** [comment]
感谢你提供的意见与技术分享。
可以加入旋转功能

**Comment by lincf0912** [comment]
已加入旋转功能 版本1.0.9

**Comment by speedpursuer** [comment]
已测试，完美！！
