### ISSUE TITLE
预览模式，多张图片全部取消后，回调的数组里面会预留一张图片。

### ISSUE THREAD

**Issue by xqzp** [lincf0912/LFImagePickerController#11]

**Comment by lincf0912** [comment]
是的，没有选中的情况下，默认发送当前张

**Comment by lincf0912** [comment]
留意下更新。下个版本新增的属性可以满足其他使用场景的需求
/// If not selected, the current image is automatically selected, Default is YES
/// 没有选中的情况下,自动选中当前张，默认是YES
@property (nonatomic, assign) BOOL autoSelectCurrentImage;

**Comment by lincf0912** [comment]
麻烦你更新一下最新版本
