### ISSUE TITLE
模态出照片选择器 navController 是白色

### ISSUE THREAD

**Issue by hongyu52155** [lincf0912/LFImagePickerController#12]
iOS 10.3
导航栏为白色，设置naviBgColor未生效。

**Comment by lincf0912** [comment]
不好意思，请临时使用
[self presentViewController:imagePicker animated:YES completion:nil];
    imagePicker.navigationBar.barTintColor = [UIColor redColor];
这种不友好的方式解决。
导航栏的样式需要调整，下个版本解决这个问题，谢谢你的反馈。

**Comment by lincf0912** [comment]
1.2.2 解决了，请更新
