### ISSUE TITLE
Select Multiple Videos

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [lincf0912/LFImagePickerController#15]
How can we select multiple videos with the checkbox icon like we can with photos and gifs?

**Comment by lincf0912** [comment]
hi，video only select single so far

**Comment by lincf0912** [comment]
maybe multiple select 、Mixed select at later

**Comment by MarcAnthonyPhotography** [comment]
Do you do custom work? There are a few options that I would like personally.
