### ISSUE TITLE
预览模式（asset对象）按钮选择后崩溃， 因为index:6

### ISSUE THREAD

**Issue by YasinZhou** [lincf0912/LFImagePickerController#16]

**Comment by YasinZhou** [comment]
因为相册中的图片没有6张

**Comment by YasinZhou** [comment]
另外如果能去掉LFMediaEditingController的必须引用就更好了

**Comment by YasinZhou** [comment]
感谢分享，已拉源码

**Comment by lincf0912** [comment]
这个崩溃是故意操作的吗？
预览模式（asset对象）的数据源是需要设置的，同样index也是；你给数据源6个，index=6，肯定崩溃了。
如果不是这样的话，麻烦你提供一下你的初始化代码。

**Comment by lincf0912** [comment]
新版本已经可以去掉LFMediaEditingController的必要引用了。
