### ISSUE TITLE
thumbnailImages未压缩到10k左右

### ISSUE THREAD

**Issue by speedpursuer** [lincf0912/LFImagePickerController#2]
lf_imagePickerController:(LFImagePickerController *)picker didFinishPickingThumbnailImages:(NSArray<UIImage *> *)thumbnailImages originalImages:(NSArray<UIImage *> *)originalImages;

此回调中的thumbnailImages好像没有压缩到10k左右，在不勾选原图的情况下，和originalImages中的标清图分辨率和大小基本一样。

**Comment by lincf0912** [comment]
首先我不清楚你是如何获取图片的大小。获取图片大小我是用UIImageJPEGRepresentation(UIImage * __nonnull image, CGFloat compressionQuality)这个方法，但这个方法的系数比较特别，不详细说明。同时这部分我也会在demo上再加上。
1、thumbnailImages：UIImageJPEGRepresentation(thumbnailImage, 0.01f) 保存到本地查看，图片在10k左右
2、originalImages：会根据UI若没有勾选原图则进行压缩，压缩在100k左右（这里的误差可能会比较大20k），不压缩的情况会根据原图实际大小获取。UIImageJPEGRepresentation(thumbnailImage, 0.75f)保存到本地查看

**Comment by speedpursuer** [comment]
用UIImageJPEGRepresentation处理应该是可以的，如果封装到里面是不是更好？：）

**Comment by lincf0912** [comment]
你仔细想想。最后需要保存图片到本地文件夹 也不可避免使用UIImageJPEGRepresentation 过渡封装了
