### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by yang94** [lincf0912/LFImagePickerController#21]
请问pods安装的版本拍照提示保存失败是什么原因

**Comment by lincf0912** [comment]
感谢你的反馈。这是一个bug，今天会修复的。明天你可以再pod update更新。如果比较赶的话，可以实现- (void)lf_imagePickerControllerTakePhoto:(LFImagePickerController *)picker代理自定义拍照与保存

**Comment by lincf0912** [comment]
已经修复 LFImagePickerController (1.2.9)
