### ISSUE TITLE
尊敬的作者您好：

### ISSUE THREAD

**Issue by yang94** [lincf0912/LFImagePickerController#23]
建议可以返回记录当前滑动图片在数组中的索引

**Comment by lincf0912** [comment]
能否细说具体需求，我不明白滑动图片回调当前索引有什么意义。

**Comment by yang94** [comment]
因为需要做长按识别图片的功能，如果不返回索引无法确定是哪张图片

**Comment by lincf0912** [comment]
我感觉你是想做图片预览器，而不是图片选择器。如果是图片预览器，你可以看看LFPhotoBrowser是否适合你。
甚至我想不明白长按识别图片的功能与LFImagePickerController回调索引有什么关系，除非你需要将长按识别图片的功能添加到LFImagePickerController，那么你可以fork，然后再实现。

**Comment by yang94** [comment]
好的，谢谢，突然发现GIf压缩后，变成静态图片了

**Comment by lincf0912** [comment]
GIf压缩? 是选择gif图片之后回调出来的2张图片都不会动？

**Comment by yang94** [comment]
感谢您百忙之中回复我的问题，原图不会，压缩图片会

**Comment by lincf0912** [comment]
我在demo上测试是没有问题的，你尝试下更新demo再试试。

**Comment by yang94** [comment]
你好，我用的就是最新的，不选择原图，Gif显示的是一张静态图

**Comment by lincf0912** [comment]
你是使用demo测试，还是使用你的项目测试的？如果在你的项目测试，请把你的初始化代码贴来看看。

**Comment by yang94** [comment]
<img width="734" alt="pianduan" src="https://user-images.githubusercontent.com/19946821/30465717-54741494-9a0b-11e7-846e-d0a017af8772.png">
sorry，最近在忙别的事情，这个是我的初始化代码片段

**Comment by lincf0912** [comment]
可以再将回调的处理代码贴出来吗？

**Comment by yang94** [comment]
<img width="500" alt="qq20170916-094739 2x" src="https://user-images.githubusercontent.com/19946821/30508212-3116ce10-9ac4-11e7-9ebf-7c69016c14bc.png">

**Comment by yang94** [comment]
![Uploading QQ20170916-094739@2x.png…]()
您好，您看一下，这里使用缩略图数据就变成展示的时候就变成静态图片，但类型仍然是Gif只是不能正常播放，如果使用原图/标清图数据不选择原图按钮Gif仍然是一个静态图片
