### ISSUE TITLE
Gif缩略数据解析出来Gif不能正常播放

### ISSUE THREAD

**Issue by yang94** [lincf0912/LFImagePickerController#24]
<img width="500" alt="qq20170916-094739 2x" src="https://user-images.githubusercontent.com/19946821/30508349-7d489c20-9ac7-11e7-9198-163f808bb51c.png">
不好意思，这个是我回调之后的代码

**Comment by yang94** [comment]
加入//    imagePicker.syncAlbum = YES; /** 实时同步相册 */
这段代码后视频不能正常预览

**Comment by lincf0912** [comment]
要不这样。你留个联系方式 QQ之类的。好吗？
这个回调代码没有问题的，关键下面的代码你是怎么实现gif

**Comment by yang94** [comment]
好的，不好意思 QQ:895802018
