### ISSUE TITLE
hello，不允许选择图片的时候，没有返回或返回按钮导致无法返回，怎么解决？

### ISSUE THREAD

**Issue by yulingyiyi** [lincf0912/LFImagePickerController#26]

**Comment by lincf0912** [comment]
麻烦提供你的初始化代码。与相关界面截图。谢谢你。

**Comment by yulingyiyi** [comment]
LFImagePickerController *imagePicker = [[LFImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];
        imagePicker.allowPickingVideo = NO;
        imagePicker.allowEditing = YES;
        imagePicker.allowTakePicture = NO;
        [self presentViewController:imagePicker animated:YES completion:^{
            imagePicker.pickerDelegate = self;
        }];
        
![img_0025](https://user-images.githubusercontent.com/23694863/32265630-d1de0c62-beb1-11e7-879a-4d8bdd8ca43b.PNG)

**Comment by lincf0912** [comment]
好的，非常感谢你的反馈。

**Comment by lincf0912** [comment]
版本1.3.4 已解决上述问题
