### ISSUE TITLE
返回图片的时候，有时候返回一个空的图片

### ISSUE THREAD

**Issue by yulingyiyi** [lincf0912/LFImagePickerController#27]

**Comment by yulingyiyi** [comment]
[results enumerateObjectsWithOptions:NSEnumerationConcurrent usingBlock:^(LFResultObject * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            UIImage *image = [(LFResultImage *)obj originalImage];
            [self upload:image];
        }];

**Comment by lincf0912** [comment]
是指UIImage *image = [(LFResultImage *)obj originalImage]; 的 image==nil 吗？
是live photo、gif、edit photo、还是普通图片？

**Comment by yulingyiyi** [comment]
icould 上的图片就返回nil
![9a809186-aed2-4ef0-bf90-ed9de9677448](https://user-images.githubusercontent.com/23694863/32312877-01d64c38-bf6e-11e7-9d94-506ecbb3c8dc.png)

**Comment by lincf0912** [comment]
明白，iCloud的图片暂时缺乏这个阶段的测试。后续版本再完善iCloud photo，不好意思。

**Comment by yulingyiyi** [comment]
demo 也是返回nil

**Comment by lincf0912** [comment]
[版本1.3.8 已修复](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.3.8)
