### ISSUE TITLE
视频编辑

### ISSUE THREAD

**Issue by Edwares** [lincf0912/LFImagePickerController#28]
iphone6s  ios11   选择相册里的视频，点编辑后内存疯涨，最后闪退

**Comment by lincf0912** [comment]
1、请问编辑的视频有多长？
2、是全部视频都这样吗？可以试试其他视频是否有这个情况。
我测试iPhone6s iOS10 5分钟的视频 相当流畅。麻烦你回答下以上问题，感谢你的反馈。

**Comment by lincf0912** [comment]
LFMediaEditingController 1.1.5已经解决内存溢出的问题
