### ISSUE TITLE
没有保存已经选过的图片，在一个相册选完图片出去之后再回来，之前选的图片都变成未选中状态。

### ISSUE THREAD

**Issue by Ryan0520** [lincf0912/LFImagePickerController#30]
没有保存已经选过的图片，在一个相册选完图片出去之后再回来，之前选的图片都变成未选中状态。

**Comment by lincf0912** [comment]
这是一个需求问题。经过多方面的考虑，这个框架的设计是这样子的。

**Comment by Ryan0520** [comment]
我说的是还没有关掉这个选择图片的界面，就仅仅是pop到上一个相册列表的界面，再进去刚刚选过图片的相册界面，就已经没有保存已经选过的图片了。这个保存记录不是基本功能吗😳还提的上需求呀？不过你的编辑库确实赞👍🏻

**Comment by lincf0912** [comment]
我理解你的意图，这也是我最初实现的效果。但这样体验效果非常差。
如果你有更好的需求，我是会采纳的，谢谢你的意见。
