### ISSUE TITLE
希望能加个选择视频时不允许选择图片，选择图片时不允许选择视频的选项，让图片、视频的选择互斥。

### ISSUE THREAD

**Issue by Insfgg99x** [lincf0912/LFImagePickerController#36]
如题

**Comment by lincf0912** [comment]
初始化时是可以设置的。

**Comment by Insfgg99x** [comment]
![image](https://user-images.githubusercontent.com/12442442/37954517-9b897440-31d8-11e8-9f40-2a54bd2b1e73.png)
没看到这个属性呢

**Comment by Insfgg99x** [comment]
请问我应该怎么做才可以让选择图片和选择视频互斥

**Comment by lincf0912** [comment]
将allowPickingImage或allowPickingVideo设置为NO即可。
如果你是想图片与视频都能看见，但只能选其一？那的确没有这个配置。旧的版本才是这样。
目前只能在初始化前决定可选类型，或者在确定完成时，对结果进行区分。

**Comment by Insfgg99x** [comment]
对，我需要同时看到视频和照片，和微信发朋友圈选图片一样，选择视频时，不能选择照片，选择照片时不能选择视频

**Comment by lincf0912** [comment]
我明白了。

**Comment by lincf0912** [comment]
[版本1.4.4](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.4.4)已支持。
具体请看demo。（imagePicker.maxVideosCount）
