### ISSUE TITLE
1.4.4选择照片和图片互斥逻辑问题

### ISSUE THREAD

**Issue by Insfgg99x** [lincf0912/LFImagePickerController#37]
还有点小问题：
我设置maxVideosCount为1，但是我可以选择多个视频，如下图：

![image](https://user-images.githubusercontent.com/12442442/38083851-6363fb70-337d-11e8-8d1a-6f28784c4f40.png)

![image](https://user-images.githubusercontent.com/12442442/38083883-7aaf9faa-337d-11e8-832d-894fea2c2565.png)

还有就是希望maxVideosCount为1的时候，选择某个视频直接进入视频预览界面（希望视频去掉对勾，直接选中进预览，类似微信），如下图所示：

![image](https://user-images.githubusercontent.com/12442442/38084259-be497488-337e-11e8-81d3-be7eff725f1c.png)
![image](https://user-images.githubusercontent.com/12442442/38084262-c1587c82-337e-11e8-8ded-0786bdaf0638.png)

**Comment by lincf0912** [comment]
感谢你的反馈！
多视频的选择问题我再测试下，预计明天会修复的。
maxVideosCount为1的时候直接进入预览界面；这个工作量不少，而且为什么必须要到预览界面才能发送也是需求问题，这个再考虑考虑。

发自我的 iPhone

**Comment by Insfgg99x** [comment]
max count值为1的时候，意味着只能选择一张，这个时候用户的预期是点了直接进入编辑界面。
就是省去勾选对勾这一步，因为1个视频是最大选择量。
对勾的意思是可以多选，UIImagePickerController单选也是这样的。
我的意思是希望在maxVideosCount为1的时候，不要显示视频的对勾，同时右下角的完成也隐藏，点击cell直接进视频预览界面，类似微信。

**Comment by lincf0912** [comment]
[版本1.4.4.1](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.4.4.1) 已修复上述问题

**Comment by Insfgg99x** [comment]
感谢感谢
