### ISSUE TITLE
大神可以在LFResultObject对象里暴露一个文件URL吗？

### ISSUE THREAD

**Issue by Insfgg99x** [lincf0912/LFImagePickerController#38]
我需要用到一个像UIImagePickerController的didFinishPickerMediaWithInfo:(NSDictionary *)info
这个info的UIImagePIckerControllerMediaURL这个东西，因为很多视频编辑，还有一些其它的业务都需要这个东西。你可以在LFResultObject的.h里暴露这个属性吗？

**Comment by lincf0912** [comment]
LFResultObject 有asset 可以获取的

发自我的 iPhone

**Comment by Insfgg99x** [comment]
是可以拿，如果有现成的URL直接用不是很爽吗

**Comment by lincf0912** [comment]
这种个别的需求不可能在框架上体现出来的。
你可以fork项目来修改。或者再回调结束后使用LFAssetManager可以轻松获取的

**Comment by Insfgg99x** [comment]
好的好的
