### ISSUE TITLE
当我设置图片为1张时，选中标志可以继续操作，即使有提示我只能选中1张

### ISSUE THREAD

**Issue by 977616908** [lincf0912/LFImagePickerController#4]
当我设置图片为1张时，选了一张之后，还可以选中第二张第三张，（选中标志可以继续操作）即使有提示我只能选中1张

**Comment by lincf0912** [comment]
感谢你的反馈，会尽快处理该问题

**Comment by 977616908** [comment]
另外发送图片时，默认的压缩比好严重。在不选择原图的情况下，基本非常小。最后：感谢lincf0912的分享

**Comment by lincf0912** [comment]
thumbnailImages：不管是否选择原图，都压缩在10k左右
originalImages：非原图100k左右
你说的压缩严重是指originalImages的图片吗？

**Comment by 977616908** [comment]
对的，我在非选择原图模式下，获取originalImages就很小。这个可以设置吗？？？
1.方法：- (void)lf_imagePickerController:(LFImagePickerController *)picker didFinishPickingThumbnailImages:(NSArray<UIImage *> *)thumbnailImages originalImages:(NSArray<UIImage *> *)originalImages infos:(NSArray<NSDictionary *> *)infos   
2.获取到的图片路径：NSString *originalFilePath = [documentPath stringByAppendingPathComponent:@"original"];
3.聊天发送图片  [self sendImageMessage:originalImages[i]];

**Comment by 977616908** [comment]
类似微信发送，他在发送图片时也不会压缩得这么厉害。

**Comment by 977616908** [comment]
麻烦帮我看下，十分感谢

**Comment by lincf0912** [comment]
部分图片压缩后的误差会很大，原因是误差率与效率，我选择了后者。
代理回调后的图片大小，会取决于你保存到本地时的入参再次决定图片大小。
UIImageJPEGRepresentation(image, 1.f) 
但我建议上还是根据demo的保存方式，下一个版本（今天）会开发压缩比例的设置，同时demo的保存方式也会调整，敬请留意

**Comment by lincf0912** [comment]
已修复 版本1.1.4。
