### ISSUE TITLE
你可以加个不压缩视频的参数吗？

### ISSUE THREAD

**Issue by Insfgg99x** [lincf0912/LFImagePickerController#40]
或者你可以告诉我改哪些代码可以不使用视频压缩吗？我不需要压缩，我尝试着改了，没改好。
视频压缩模糊，这个很伤啊，直接导致视屏需求的人不能用了！

**Comment by lincf0912** [comment]
可以将LF_VideoUtils类里面的AVAssetExportPresetMediumQuality修改为其他preset试试。

**Comment by Insfgg99x** [comment]
AVAssetExportPresetMediumQuality改为AVAssetExportPreset1280x720就好了，9.7MB压缩至6.7MB，完美！谢谢
