### ISSUE TITLE
新版本比旧版本性能降低了

### ISSUE THREAD

**Issue by StudentMJ** [lincf0912/LFImagePickerController#42]
1.4.1版本之后，图片选择器的初始加载时间慢了很多，所以我现在一直在用1.4.1版本，还有就是有的图片上传成功后链接地址打不开。

**Comment by lincf0912** [comment]
好的，感谢你的反馈。为了更加准确定位到问题，请你配合回复以下问题：
1、请问你的相册数量大概是多少？
2、图片上传成功后链接地址打不开是什么意思？好像跟LFImagePickerController没有关系。
