### ISSUE TITLE
doneBtnTitleStr文字不同界面文字不一样怎么修改

### ISSUE THREAD

**Issue by wyt666** [lincf0912/LFImagePickerController#43]
doneBtnTitleStr文字不同界面文字不一样怎么修改

**Comment by wyt666** [comment]
@lincf0912 doneBtnTitleStr文字不同界面文字不一样怎么修改

**Comment by lincf0912** [comment]
doneBtnTitleStr已经过时了
请使用新的方式修改文字
复制LFImagePickerController.bundle\LFImagePickerController.strings到项目中，修改对应的值即可；详情见DEMO；
希望对你有帮助

**Comment by wyt666** [comment]
@lincf0912 这样改的话，整个项目用到的地方文字都会变成一样的了，怎么才能在不同的地方设置不同的文字呢

**Comment by lincf0912** [comment]
我并不理解你所描述的情况。
你是想改变右下角那个绿色按钮的文字吗？

**Comment by wyt666** [comment]
@lincf0912 是的，比如和微信一样，在朋友圈选择图片右下角那个绿色按钮显示完成，在聊天界面选择图片右下角那个绿色按钮显示发送，

**Comment by lincf0912** [comment]
明白了，我并没有考虑到这种情况的出现。

**Comment by lincf0912** [comment]
如你所说，暂时只能整个项目的文字统一

**Comment by wyt666** [comment]
恩，那好吧。还有个小问题就是“预览”那个按钮点击区域有点小不太容易点击

**Comment by lincf0912** [comment]
感谢你的反馈，这2个问题如有必须，我将会计划在下一个版本。

**Comment by wyt666** [comment]
好的，谢谢

**Comment by lincf0912** [comment]
[版本1.4.7](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.4.7)支持不同界面文字显示
请预览LFLayoutPickerController.h 的属性描述
