### ISSUE TITLE
图片编辑后清晰度下降严重

### ISSUE THREAD

**Issue by StudentMJ** [lincf0912/LFImagePickerController#44]
1.4.6版本性能改善明显，之前还有个问题忘了提，就是图片编辑后，不管是否勾选原图，发送出去的图片清晰度都很低，跟微信差距很明显，后来我自己写的选择器，并且修改了LFMediaEditingController，新增了获取透明底色的纯编辑图片，在完成的时候，如果有纯编辑图片，就将纯编辑图片绘制到原图上，这样就不损失原图的清晰度了，只不过对于尺寸比较大的图片，在绘制过程会占用比较大的内存，目前我就想到这一种方法来保证编辑后原图不失真。不知道作者在1.4.6版本中有没有优化这方面，如果没有优化，我就得继续用自己写的选择器了。

**Comment by lincf0912** [comment]
这个问题应该是提到 LFMediaEditingController 项目的。
你更新LFImagePickerController试试看，目前最新版本是1.4.7.1。同时也会更新LFMediaEditingController框架的。
最新的LFMediaEditingController框架改变了原有的截屏模式，详情请看LFMediaEditingController的Release页面

**Comment by lincf0912** [comment]
顺便一提，使用LFImagePickerController来编辑图片后得到的图片质量不能与实际在相册中的图片质量比较。编辑图片质量<=实际图片质量。原因是LFImagePickerController的预览界面并非展示原图的质量。
目前LFMediaEditingController是保证了编辑图片的质量的。但LFImagePickerController并没有提供原图质量给LFMediaEditingController。
