### ISSUE TITLE
合成gif的bug

### ISSUE THREAD

**Issue by xinge1** [lincf0912/LFImagePickerController#45]
# 选择2个尺寸不一样的图片合成gif就会出现这样的情况。
![avatar](http://wx3.sinaimg.cn/mw690/0060lm7Tly1frlbqp99evj30j60y3tiw.jpg)

**Comment by lincf0912** [comment]
如果你没有修改demo代码的话，麻烦你提供下测试的机型与步骤。
感谢你的反馈。

**Comment by xinge1** [comment]
这个是在模拟器ios11中的bug，在真机中没出现。
还有个问题，不知道是不是bug。
Live Photo相册中如果是HDR相片，在选择相片页面不显示 Live 图标，点击进入预览不播放live

**Comment by lincf0912** [comment]
好的，我这边测试一下 Live Photo HDR相片。感谢你的反馈

**Comment by xinge1** [comment]
已经找到原因了，当图片同时是LivePhoto和HDR时
asset.mediaSubtypes == 10

**Comment by lincf0912** [comment]
同学。你很棒哦！

发自我的 iPhone

**Comment by lincf0912** [comment]
这个issus已经修复了，请更新到[版本1.5.0](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.0)
