### ISSUE TITLE
照片处理所耗时间问题

### ISSUE THREAD

**Issue by EricDengR** [lincf0912/LFImagePickerController#46]
选完照片后处理时间有点长，选了9张手机拍的照片，“正在处理... ” 花费的时间大概有二十几秒了，请问大神这种情况怎么进行优化。

**Comment by lincf0912** [comment]
请留意下一个版本，我会适配不同的操作逻辑调整处理的数据。
暂时的话你可以这样设置：
imagePicker.allowPickingOriginalPhoto = NO;
imagePicker.isSelectOriginalPhoto = YES;
如果不需要缩略图：
imagePicker.thumbnailCompressSize = 10000.f;
试试看。

**Comment by EricDengR** [comment]
好的，多谢。顺便问一下，下一个版本大概什么时候上线，期待中...

**Comment by EricDengR** [comment]
设置完缩略图大小之后，处理速度确实有显著的提升。

**Comment by lincf0912** [comment]
[版本1.4.9](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.4.9)

imagePicker.thumbnailCompressSize = 0.f; /** 不需要缩略图 */

**Comment by EricDengR** [comment]
ok，多谢
