### ISSUE TITLE
选择单个图片时的问题

### ISSUE THREAD

**Issue by xiaoxiaowan** [lincf0912/LFImagePickerController#47]
老的版本使用 MaxImagesCount 为1 可以直接选择单张照片，现版本去掉了这个功能？

**Comment by lincf0912** [comment]
你好，并没有去掉的。这是一个issue。感谢你的反馈。
请你暂时在初始化的时候指定maxImageCount。
[[LFImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];
该问题已解决但未发布。

**Comment by xiaoxiaowan** [comment]
这个问题在1.5.1中仍然存在

**Comment by lincf0912** [comment]
能不能详细描述这个问题？

**Comment by xiaoxiaowan** [comment]
![new2](https://user-images.githubusercontent.com/13130944/41699960-efc45a66-7558-11e8-9248-67e6f0c3980c.jpeg)
![old2](https://user-images.githubusercontent.com/13130944/41699961-f0130a12-7558-11e8-9bcc-006969b69e60.jpeg)
![new1](https://user-images.githubusercontent.com/13130944/41699962-f0aef4c2-7558-11e8-94a1-c987567bc9d5.jpeg)
![old1](https://user-images.githubusercontent.com/13130944/41699963-f1218938-7558-11e8-91c5-2d556090aa80.jpeg)


带勾的是老版本的选择单张图片的效果、不带勾的是新版本MaxImagesCount设置为1时的效果

**Comment by xiaoxiaowan** [comment]
也就是现版本选择单张图片的话不可以在图片列表的时候选中某张图片，必须要点进去才可以选中

**Comment by lincf0912** [comment]
对的。现在单张去掉了选中的操作，修改为点进去才能发送。

**Comment by xiaoxiaowan** [comment]
点进去的页面也变掉了，右上角的选择按钮也没有了，个人感觉还是在外面列表可以选择对用户比较友好一点^-^

**Comment by lincf0912** [comment]
是的。点进去的页面如果只是选择一张，再有选择按钮就多此一举（选错了还需要去掉选择才能再选）。
这个设计主要是跟随微信的用户习惯。兼容微信的朋友圈模式。

**Comment by xiaoxiaowan** [comment]
我建议选择单张图片时将列表中的选择按钮放出来，不然选择单张图片每次都要点进去才可以选择，对用户不太友好，纯属个人意见，如有不妥、还望海涵

**Comment by lincf0912** [comment]
其实2种模式都有人跟我提过。我也考虑2种方式的平衡，虽然说可以兼容2种方式的显示，但我又觉得很花俏多余。但这2种方式各有千秋，我选择了跟随微信的做法😉。希望理解。
或许你是对UI有强烈的要求，可以fork项目来修改，这个调整幅度并不大的。GOOD LUCK。

**Comment by xiaoxiaowan** [comment]
ok，我自己搞一份改下好了，多谢分享
