### ISSUE TITLE
创建的mp4视频文件有点问题

### ISSUE THREAD

**Issue by xinge1** [lincf0912/LFImagePickerController#48]
![simulator screen shot - iphone 7 - 2018-07-02 at 13 35 43](https://user-images.githubusercontent.com/7411625/42146820-f05f5982-7d8f-11e8-9a5c-469c577e81a3.png)

![simulator screen shot - iphone 7 - 2018-07-02 at 13 35 54](https://user-images.githubusercontent.com/7411625/42146829-fb799dd2-7d8f-11e8-8684-c47728fba73a.png)
看到了吗，右边会有绿色或其他颜色的条纹

**Comment by lincf0912** [comment]
可能是你的图片存在问题。你尝试用真机拍几张试试

**Comment by lincf0912** [comment]
[版本1.5.4](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.4)已修复mp4的创建，请更新版本。
