### ISSUE TITLE
快速连续不断的勾选和取消勾选 (刷新问题吧 )

### ISSUE THREAD

**Issue by 15757857346** [lincf0912/LFImagePickerController#49]
奔溃点 ：
[self.collectionView performBatchUpdates:^{
            [self.collectionView reloadItemsAtIndexPaths:indexPaths];
        } completion:^(BOOL finished) {
            [self.collectionView scrollToItemAtIndexPath:indexPaths.lastObject atScrollPosition:UICollectionViewScrollPositionCenteredHorizontally animated:YES];
        }];

**Comment by kllie** [comment]
![1531744958538](https://user-images.githubusercontent.com/16185755/42759236-dc4a4100-8938-11e8-8bd6-4ed5b07df127.jpg)

**Comment by lincf0912** [comment]
你很棒哦。这个问题我已经解决了。最近还有一个初始化的接口新增。我会尽快发布版本。

发自我的 iPhone

**Comment by lincf0912** [comment]
[版本1.5.3](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.3)
