### ISSUE TITLE
关于y轴距离偏移问题

### ISSUE THREAD

**Issue by kllie** [lincf0912/LFImagePickerController#50]
![simulator screen shot - iphone x - 2018-07-16 at 20 05 17](https://user-images.githubusercontent.com/16185755/42758554-89732da4-8936-11e8-8ef8-518f69ff3079.png)
@lincf0912  你好大神，如果是当前控制器用Nav管理的时候，执行self presentViewController:imagePicker的时候，展示区域会向下偏移导航条的高度。看了一下原因，tableView在创建的时候，偏移了导航条高度。

**Comment by lincf0912** [comment]
![iphonex](https://user-images.githubusercontent.com/10151410/42791244-1afee572-89a2-11e8-8fdf-96bbd8dee566.gif)
我从demo上添加了导航栏，没有出现上述问题。
如果你已经是合并到项目的话，麻烦你检查下项目导航栏的全局设置。
或者你可以创建一个新项目来测试。

**Comment by kllie** [comment]
问题已解决，确实是我这里导航条设置的问题。

**Comment by Yanyinghenmei** [comment]
- (CGFloat)navigationHeight
{
    CGFloat top;
    /*
     相对于window的位置:
     非iPhone X上, controller.view.origin.y == 0 或 controller.view.origin.y == 64
     在iPhone X上, controller.view.origin.y == 44 或 controller.view.origin.y == 88
     所以 大于 44 表明 controller.view 原点是从 navigationBar 的底部开始的
     */
    if ([self.view convertPoint:self.view.origin toView:[UIApplication sharedApplication].delegate.window].y > 45) {
        top = 0;
    } else {
        top = CGRectGetMaxY(self.navigationController.navigationBar.frame);
        return top;
    }
    return top;
}

**Comment by lincf0912** [comment]
@Yanyinghenmei  👏如果只是iPhone竖屏的话，这样修改是可以的。

**Comment by Yanyinghenmei** [comment]
@lincf0912 确实, 我只考虑了竖屏.

**Comment by lincf0912** [comment]
还有iPad的横竖屏 😜
