### ISSUE TITLE
选择视频， isDegraded 返回 YES 时  getVideoResultWithAsset 方法 completion 回调不触发

### ISSUE THREAD

**Issue by frankxzx** [lincf0912/LFImagePickerController#52]
https://github.com/lincf0912/LFImagePickerController/blob/53707012a7c14479e1191bd060e0c64663a3d1a0/LFImagePickerController/LFImagePickerController/class/manager/LFAssetManager.m#L1041

**Comment by lincf0912** [comment]
这个没毛病。
你的情况是isDegraded没有等于NO的吗？

**Comment by frankxzx** [comment]
@lincf0912 是的 isDegraded 会有返回 Yes 的情况， 而 if else 分支判断没有触发 completion 回调。所以会出现 完成选择后一直处于 「正在加载」的状态

**Comment by lincf0912** [comment]
明白了。但我想了解更多。你的测试设备，视频来源（拍摄/导入），视频类型（慢动作）？
isDegraded一般来说会有YES与NO的，但只会出现YES的情况我是没有遇到过。

**Comment by lincf0912** [comment]
@frankxzx 你的所有视频都是这样子吗？

**Comment by frankxzx** [comment]
@lincf0912 抱歉拖了这么久才回复你，这边的测试设备是  真机 iPhone 6 iOS 11.2.6，所有的视频回调都是 isDegraded = YES; 无论是否有沙盒缓存。

**Comment by lincf0912** [comment]
@frankxzx 所有的视频回调的isDegraded都会有YES和NO的。你的就只有YES。没有NO的情况吗？

**Comment by frankxzx** [comment]
@lincf0912 测试到现在的情况，是的

**Comment by lincf0912** [comment]
好的。我将尽快修复这个问题。感谢你的反馈。

**Comment by frankxzx** [comment]
LFImagePickerController 应该是开源里功能最完整的相册库了，非常感谢 👍
