### ISSUE TITLE
调用压缩视频方法，导致视频损坏

### ISSUE THREAD

**Issue by wkff** [lincf0912/LFImagePickerController#54]
压缩完之后，部分转为mp4的视频损坏并无法播放。

**Comment by lincf0912** [comment]
请问那些部分视频是非系统拍摄的吗？
你可以提供未压缩之前的视频文件给我测试吗？

**Comment by wkff** [comment]
从社交软件上保存下来的短视频。测试发现如果原文件是mp4转出来没有问题，如果不是就可能会出问题。
我把Video的exportSession.outputFileType改成AVFileTypeMPEG4，现在好点了。

**Comment by lincf0912** [comment]
@wkff 你不是保存到相册吗？我没有考虑到LF_VideoUtils给非相册的视频使用的。

**Comment by wkff** [comment]
@lincf0912 是通过其他软件保存到相册的，我们的应用从相册读出来,读取就用的你的demo上的都正常。用了LF_VideoUtils压缩后上传到服务器, 下载下来电脑手机都打不开。

**Comment by lincf0912** [comment]
@wkff 意思是你没有使用LFImagePickerController，只是使用框架的其他类来协助实现吗？我比较关心的是LFImagePickerController的问题。使用LFImagePickerController选择视频会压缩的。它通过回调给的视频不能播放吗？

**Comment by a407184508** [comment]
如何让视频不压缩呀？

**Comment by lincf0912** [comment]
视频是必须要压缩的。你可以选择最高的压缩参数；这样的话你可能认为它是不压缩了。

**Comment by a407184508** [comment]
参数怎么设置的？那个string吗？
