### ISSUE TITLE
当相册没图片的时候 拍照按钮被隐藏 

### ISSUE THREAD

**Issue by 15757857346** [lincf0912/LFImagePickerController#55]
上次忘记跟你说了 我刚新买个手机 相册没照片的 LFImagePickerController界面的拍照按钮无法显示

**Comment by lincf0912** [comment]
mark

**Comment by lincf0912** [comment]
[迟来的更新1.5.5.1](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.5.1) 已修复
