### ISSUE TITLE
获取 iCloud 图片资源时， imageData 为 nil 的情况

### ISSUE THREAD

**Issue by frankxzx** [lincf0912/LFImagePickerController#57]
https://github.com/lincf0912/LFImagePickerController/blob/97c38cba82f5416eebeb7e8aa956165d7073ac62/LFImagePickerController/LFImagePickerController/class/manager/LFAssetManager.m#L814

感觉这是一个普遍存在的问题，很对 app 有这样的情况，应该是苹果的锅 PHImageManager requestImageDataForAsset 请求高清大图会出现失败。是否有什么好的方案可以避免

**Comment by lincf0912** [comment]
你可以提供一下“高清大图”来测试一下吗？我测试都正常。
