### ISSUE TITLE
关于内存释放的问题

### ISSUE THREAD

**Issue by 734566743** [lincf0912/LFImagePickerController#58]
在测试中，我选中了9张图片。点击完成。xcode提示内存警告，我看内存和cpu，内存在415.7M左右波动。如果这时候再继续选择图片，多操作几次，会导致闪退。麻烦楼主看看，急

**Comment by 734566743** [comment]
方便留个联系方式嘛？有些问题想请教一下。或者直接加我qq:734566743。万分感谢

**Comment by lincf0912** [comment]
[版本1.5.8](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.8)
优化对内存的使用问题
