### ISSUE TITLE
编辑后的图片上下多了条黑边

### ISSUE THREAD

**Issue by speedpursuer** [lincf0912/LFImagePickerController#6]
如下图（只加了文字），在白底下看很明显，望修复。
![img_0001 jpg](https://cloud.githubusercontent.com/assets/1818577/25552114/0eb6d158-2cc4-11e7-9e44-34eafbb96a39.jpeg)

**Comment by lincf0912** [comment]
我这边没有这个问题，能详细说明下吗？是使用什么机型测试？

**Comment by lincf0912** [comment]
已处理，版本1.1.5
