### ISSUE TITLE
该第三方可以只显示视频/选择视频（视频选择器）？

### ISSUE THREAD

**Issue by 15757857346** [lincf0912/LFImagePickerController#61]
唤起LFImagePickerController 界面上只有视频 没有图片  建议加一个属性  @property (nonatomic,assign) BOOL onlyAllowPickingVideo; 希望作者大大更新一下下哈

**Comment by lincf0912** [comment]
/// Default is YES, if set NO, user can't picking video.
/// 默认为YES，如果设置为NO,用户将不能选择视频
@property (nonatomic, assign) BOOL allowPickingVideo;

/// Default is YES, if set NO, user can't picking image.
/// 默认为YES，如果设置为NO,用户将不能选择发送图片
@property (nonatomic, assign) BOOL allowPickingImage;

属性比较多。请细心看头文件。

**Comment by 15757857346** [comment]
好吧  尴尬了  感谢作者大大
