### ISSUE TITLE
正常模式 选择图片崩溃问题

### ISSUE THREAD

**Issue by 360229205** [lincf0912/LFImagePickerController#62]
选择 1 2 3  三张 进入浏览界面
点击左下角预览进浏览界面
（直接点图片进入浏览界面没问题， 原因是下部预览框取消勾选会消失）
第2张 取消选择 
第3张 取消选择
再重新勾选第3张  崩溃

LFPhotoPreviewController.m  612行
崩溃的地方
                NSInteger index = [_previewBar.dataSource indexOfObject:model];
                if (index != NSNotFound) {
                    [imagePickerVc.selectedModels insertObject:model atIndex:index];
                } else {
                    [imagePickerVc.selectedModels addObject:model];
                }

**Comment by lincf0912** [comment]
感谢你的反馈。

**Comment by 360229205** [comment]
photoPreviewVc.alwaysShowPreviewBar 这个问题
直接点图片进去浏览的时候 取消勾选  下面预览框里面会消失 所以没问题
点左下角预览进去的时候 alwaysShowPreviewBar这个 = yes
取消勾选 下面的预览框里面不消失  估计是数据源没删除 
我还没仔细看

**Comment by lincf0912** [comment]
是的。我已经了解到问题了。你很认真。谢谢你。

**Comment by lincf0912** [comment]
[版本1.5.8](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.8)
解决问题。
