### ISSUE TITLE
一些不成熟的小建议，建议保留此问题，持续更新

### ISSUE THREAD

**Issue by 360229205** [lincf0912/LFImagePickerController#63]
1、编辑模式，每笔操作完之后浮层面板会立即显示出来，影响下一笔操作，可以参考微信延迟1秒。
(主要是针对浮层下区域进行编辑的时候，比如在屏幕最底部浮层下面画一个箭头，刚画了一笔，浮层又出来了)

2、编辑模式下，超长图，没有左右铺满屏幕，只是一条细长图，无法编辑。（能否优先考虑）

3、X以及以上机型 顶部会遮挡无法编辑。

4、返回图片目前只有缩略和正常（正常分标准和原图），建议多添加一个原图属性，一共缩略，正常、原图三种，不勾选原图，原图为nil，方便使用者知道此图是否为带原图的图片。
(对于一些超长图，缩略不清楚，直接原图又太消耗流量，所以外部是缩略，点开是标准，下部有个“查看原图”的选项，点击之后才会加载原图，不过 这个也不是多大的问题，LOL)

**Comment by lincf0912** [comment]
1、可以考虑的。感觉作用不算太大。体验上可能提升那么一点点。
2、X的适配仍需要磨合，尽量抽时间。
3、区分3种没有意义。提供给UI的界面无非就是小图与大图，若调整.imageCompressSize=∞，那么标清与原图就根本没有区别了，而且使用内存上也是有压力的。

不得不说，你是有想法的。👍💡
