### ISSUE TITLE
普通图片预览模式缩放位置不对，超长图无法编辑，以及一个偶现崩溃

### ISSUE THREAD

**Issue by 360229205** [lincf0912/LFImagePickerController#64]
1、预览界面图片缩放后位置不正确。

2、预览界面超长图没有左右铺满屏幕，编辑模式超长图同样问题，如果手动放大图片，那画笔会跟着放大，造成无法编辑图片。

3、图片选择完成确定偶现2次崩溃，会一直显示正在处理中，一直在转圈，
LFPhotoPickerController   561行 dispatch_globalQueue_async_safe  数组越界    具体原因还在看，和系统版本应该没有关系
![img_0335](https://user-images.githubusercontent.com/17464695/49373244-430db080-f738-11e8-8406-f0e2169573e6.PNG)
![img_0336](https://user-images.githubusercontent.com/17464695/49373248-43a64700-f738-11e8-95fe-279f2d25cb74.PNG)
![img_0337](https://user-images.githubusercontent.com/17464695/49377129-45760780-f744-11e8-8369-edcffe014ff1.PNG)

**Comment by 360229205** [comment]
崩溃找到原因了，lf_fastestCompressImageSize 这个压缩方法中，如果不需要压缩的话，能直接返回nil，造成了sourcedata为空。

**Comment by 360229205** [comment]
大佬能不能帮我看下编辑模式超长图放大问题 这个我不知道在哪改
浏览模式 还能根据你的判断宽为50的时候 放大 编辑模式没有

**Comment by lincf0912** [comment]
很感谢你反馈的问题。
编辑模式算是另外一个框架实现的。比较复杂的是与剪裁时的显示会有关系。其实当初我也设想是像预览框架的模式的，但这毕竟选择图片才是主要功能，所以我并没有在预览上兼容太多的情况。
我会再兼容类似长图的图片的。但是这个兼容需要点时间来更新它。

**Comment by lincf0912** [comment]
问题1，错位的情况应该是模拟器会出现的问题。点一下屏幕的任意地方就可以了。

**Comment by lincf0912** [comment]
[版本1.5.9](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.5.9)已经解决了上述问题。至于长图的编辑问题 [LFMediaEditingController 版本1.2.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.6)已兼容了
