### ISSUE TITLE
今天测试过程中遇到一个bug, LFPreviewBar.m 中- (void)setSelectAsset:(LFAsset *)selectAsset {}这个方法中indexPaths可能会装进相同的NSIndexPath对象, 导致崩溃, 几率很小, 还有个建议就是贴图那再追加一个按钮, 用户可以用自己相册的图片做贴图这样更完美了就, 感谢大神的无私分享

### ISSUE THREAD

**Issue by SnailLoveSmile** [lincf0912/LFImagePickerController#69]

**Comment by lincf0912** [comment]
这个建议很好。
可以详细说一下怎么样的操作？

**Comment by SnailLoveSmile** [comment]
贴图数组中加一个图似添加按钮的图片, 点击这个按钮图片最后一个按钮进入LFImagePickerController选择一个图片编辑后返回这图片作为贴图, 对于二次的这个LFImagePickerController隐藏添加按钮, 防止多次进入 (ps: 开发过程中拍照后新增的图片不知道怎么直接选中, 只是syncAlbum将其展示, 希望大神考虑下)

**Comment by lincf0912** [comment]
现在你可以更新它。它已经支持相册的贴图了。[version 1.4.2](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.2)
关于编辑的issue，请提交到[这里](https://github.com/lincf0912/LFMediaEditingController/issues)
