### ISSUE TITLE
可以考虑增加GIF支持吗？ 从TZ上更新一些代码就可以了。

### ISSUE THREAD

**Issue by andyden9** [lincf0912/LFImagePickerController#7]
不过不能完全使用他的逻辑，详见：https://github.com/banchichen/TZImagePickerController/pull/460

**Comment by andyden9** [comment]
不好意思没看到  谢谢啊 我来测试

**Comment by lincf0912** [comment]
TZImagePickerController 的GIF支持有弊端 仅是后缀为.gif 就认为是GIF图片。

**Comment by andyden9** [comment]
对 应该用 0x47来判断 而且，那个作者不更新了。。。

**Comment by lincf0912** [comment]
fork 自己弄 😊
