### ISSUE TITLE
某些gif图片不会动  但是手机相册能动里

### ISSUE THREAD

**Issue by 360229205** [lincf0912/LFImagePickerController#71]
我看了下 
dataUTI  是public.jpeg
(__bridge NSString *)kUTTypeGIF 是 com.compuserve.gif
两个不对不上   能判断到是gif图     然后就不知道怎么解决了
手机相册里面这张图片是能动的     在图片选择器里面就不动了

**Comment by lincf0912** [comment]
理论上。手机相册除了livephoto，其它图片都不会动的。如果你有一些动图在选择器内不会动的话。可以发送给我研究一下。

发自我的 iPhone

**Comment by a970891** [comment]
我也遇到这个问题, 如果方便的话交流一下
部分gif图片本身用系统相册是没问题的, 用lf框架调出后再用flanimationimageview或者yyanimationimageview都没法正常播放
@lincf0912 
QQ2279171358

**Comment by lincf0912** [comment]
可以的话。麻烦你提供一下那张动图。它是如何保存到相册的。谢谢

**Comment by a970891** [comment]
@lincf0912 不是一张, 是很多张, 我是从手机百度保存下来的, 这里回复似乎不能贴图? 能否邮箱或者好友传递

**Comment by a970891** [comment]
我刚才仔细看了一下, 用手机QQ选择的话, 他直接不会贴上gif标签, 选出来也是静态图, 很奇怪

**Comment by lincf0912** [comment]
某一张就行，可能它们都问题都是一样的。
这里是可以贴图的。
我添加好友。但是没有通过。

**Comment by lincf0912** [comment]
尝试一下这个版本。[版本1.6.4](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.6.4)
