### ISSUE TITLE
你好，在编辑模式下，编辑页面导航取消和确定按钮被导航遮挡

### ISSUE THREAD

**Issue by zfx5130** [lincf0912/LFImagePickerController#73]
在Demo里面没有遮挡问题， 但放在自己项目里面，仅仅就是集成调用， 却在编辑图片页面，上放没出现取消和确定， 怎么配置

**Comment by zfx5130** [comment]
我在 LFBaseEditingController 的viewDidAppear加入“[self.navigationController setNavigationBarHidden:YES];” 就可以了， 希望能修改并更新下pod,

**Comment by lincf0912** [comment]
1、这个issue不应该提到这里。
2、参考demo的方法（PhotoViewController.m --> photoEditing方法）。如果你是跟demo一样，可能是你项目在推送界面的时候重置导航栏的某些状态了。或许这是你的项目的需求设计没有考虑的情况，应该调整兼容。
3、并不是所有项目都是使用[self.navigationController setNavigationBarHidden:YES];来隐藏导航栏的。所以需要在push editingController时，根据自身项目的设计来隐藏导航栏。

**Comment by zfx5130** [comment]
在编辑状态下，图片滤镜默认是显示因为 orignal curve fade 等。 这些怎么能够设置为中文
@lincf0912

**Comment by lincf0912** [comment]
这些不能改了。是我忽略的。我将在下一个版本添加上，可以在LFMediaEditingController.strings修改。

**Comment by zfx5130** [comment]
好的,thanks
