### ISSUE TITLE
ios13适配

### ISSUE THREAD

**Issue by piepie314** [lincf0912/LFImagePickerController#74]
你好，在iOS13真机环境中会出现以下情况：在最近项目页面点击左上角返回按钮，显示的页面没有任何数据，并且任何点击事件都无法响应，请问我该如何处理？

**Comment by lincf0912** [comment]
iOS13未能第一时间测试。
最近项目页面是指九宫格的选择界面吗？如果可以的话麻烦你截图描述一下。
我会尽快测试iOS13.

**Comment by piepie314** [comment]
![IMG_0087](https://user-images.githubusercontent.com/608177/64933079-d2262800-d875-11e9-995e-ed767baef490.PNG)
![IMG_0088](https://user-images.githubusercontent.com/608177/64933080-d3efeb80-d875-11e9-8505-a59138ab221b.PNG)

可能是iOS 13 生命周期更改导致此情况发生

        if (_pushPhotoPickerVc) {
            LFPhotoPickerController *photoPickerVc = [[LFPhotoPickerController alloc] init];
            [self setViewControllers:@[albumPickerVc, photoPickerVc] animated:YES];
        } else {
            [self setViewControllers:@[albumPickerVc] animated:YES];
        }
        setViewControllers 可能与iOS 13 生命周期不匹配，导致界面为空，以上是我的分析，不知道是否正确 =。=

**Comment by lincf0912** [comment]
感谢你的反馈。我将尽快测试iOS13并修复它。

**Comment by lincf0912** [comment]
你好。我今天测试的iOS13正式版，它仅存在一些样式的问题。你描述的问题我并没有重现。
而且你的截图与iOS13的present界面的显示有一些差距。我测试的iOS13present是不全屏的。

**Comment by piepie314** [comment]
To Whom it may concern,


你好，我当时使用的是 iOS 13 beta版本，正式版本我没有测试过。

present 全屏在 iOS 13上需要手动设置


if #available(iOS 13, *) {
            viewController.modalPresentationStyle = .fullScreen
        }

明天我会在正式版本中 尝试一下。

谢谢


Yours sincerely

piepiewang

**Comment by piepie314** [comment]
你好，经测试此情况在iOS13正式版的出现概率极小，但还是有几率出现在iPhone XR上，目前不知道是不是机型原因，我会继续观察。

**Comment by lincf0912** [comment]
框架调整了UI，你可以更新框架版本1.6.8.1试试。
