### ISSUE TITLE
13.2.2 点击所有照片按钮,界面卡死

### ISSUE THREAD

**Issue by zhanglexiaoge** [lincf0912/LFImagePickerController#76]
![GitHub Logo](/Users/weiyeming/Desktop/iOSHC110115734521457710.jpg)

**Comment by zhanglexiaoge** [comment]
![iOSHC110115734521457710](https://user-images.githubusercontent.com/16223789/68564831-a3e75200-048c-11ea-8159-7233a07c0590.jpg)

**Comment by zhanglexiaoge** [comment]
@lincf0912 
iOS最新系统,直接会卡死

**Comment by lincf0912** [comment]
感谢你的反馈。我暂时未能重现这个问题。正在排查中。

**Comment by zhanglexiaoge** [comment]
@lincf0912 运行demo,正常模式,点击所有照片卡死,暂时发现的就是iOS系统版本13.2.2会出现这个问题

**Comment by lincf0912** [comment]
我一直测试iPhone 6 13.2.2，没有卡死的现象。默认相册是叫“最近项目”。它跟你的不一样。

**Comment by lincf0912** [comment]
你目前的问题是，点击了顶部的标题时，没有出现菜单，然后点那里都没有反应。是这样吗？

**Comment by zhanglexiaoge** [comment]
是的 正常来说点击顶部的标题时,会出现菜单 所有照片 自拍 动图 实况照片等等 ,但是(iPhone 8p iPhone Xs  max) 13.2.2 系统 点击了顶部标题,这个界面滑动,点击都没有反应 (卡死),你有qq吗,我可以录个视频给你 @lincf0912

**Comment by zhanglexiaoge** [comment]
https://pic2.hanmaker.com/im/files/iOSHC110115738067340500.mp4?videoHeight=720#videoWidth=1280  你可以看下这个视频 ,只要一点击顶部,就卡死

**Comment by lincf0912** [comment]
收到了。我只能怀疑是LFAlbumTitleView出现了问题，didMoveToSuperview这个方法会通过getCurrentVC来获取当前VC。可能就是这个方法死循环。但是我无法调试它。我测试都是正常的，而我并没有你测试的设备来重现它。

**Comment by lincf0912** [comment]
我今天会提交一个版本来解决这个问题。

**Comment by lincf0912** [comment]
更新[版本1.6.9](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.6.9)试试

**Comment by zhanglexiaoge** [comment]
谢谢已经OK了
