### ISSUE TITLE
iOS13 慢动作视频点击顶部menu卡死

### ISSUE THREAD

**Issue by cocoaroger** [lincf0912/LFImagePickerController#77]
<img width="1230" alt="WechatIMG259" src="https://user-images.githubusercontent.com/7246482/70208544-ceb18700-1768-11ea-8336-b6a4bb4e86e3.png">

**Comment by lincf0912** [comment]
应该是跟这里没有关系的。你更新框架到版本1.6.9.2试试。

**Comment by cocoaroger** [comment]
使用的是1.6.9.2, 确实是添加慢动作的视频后必现这个问题, 系统版本是13才会, 12不会

**Comment by lincf0912** [comment]
好的。感谢你的反馈。

**Comment by lincf0912** [comment]
暂时还没有找到比较好的解决方案。我将慢动作视频的真实时间屏蔽了。麻烦你更新1.6.9.3

**Comment by lincf0912** [comment]
版本1.6.9.4，修复了慢动作获取真实时间卡死的问题。

**Comment by cocoaroger** [comment]
好的, 感谢

**Comment by cocoaroger** [comment]
> 版本1.6.9.4，修复了慢动作获取真实时间卡死的问题。

好的,感谢
