### ISSUE TITLE
你好大神, iPhone6 系统9.3.5, 首先UI重叠, 并且present选图界面, 所有点击事件不执行, 只能杀死程序

### ISSUE THREAD

**Issue by SnailLoveSmile** [lincf0912/LFImagePickerController#78]
![IMG_0290(20191205-150526)](https://user-images.githubusercontent.com/33648940/70211712-bba2b500-1770-11ea-8b5e-d531785a5b53.JPG)
![截屏2019-12-05下午3 06 10](https://user-images.githubusercontent.com/33648940/70211741-cbba9480-1770-11ea-9250-0526a6303631.png)

**Comment by lincf0912** [comment]
麻烦你更新框架到版本1.6.9.2。

**Comment by SnailLoveSmile** [comment]
恩, 好的 我这边试试, 谢谢那么及时的回复

**Comment by SnailLoveSmile** [comment]
没有解决...
