### ISSUE TITLE
iOS 9系统, ui重叠, 点击无响应的问题最新版本没有解决, 上个提出的bug, 被我一不小心close了,尴尬, 只能再发起一个了

### ISSUE THREAD

**Issue by SnailLoveSmile** [lincf0912/LFImagePickerController#79]

**Comment by lincf0912** [comment]
收到。我尽量找到iOS9的机型测试一下。

**Comment by lincf0912** [comment]
它的顶部仍然重叠吗？

**Comment by SnailLoveSmile** [comment]
明天周一我让他们问下这个客户, 不好意思 刚看到

**Comment by SnailLoveSmile** [comment]
忘了, 我没更新最新库, 这个要升级晚点回复你了,谢谢大神,辛苦了

**Comment by lincf0912** [comment]
你更新应该是解决了的。

发自我的 iPhone

**Comment by SnailLoveSmile** [comment]
恩恩,  上次的那个使用人员升级了iOS 13, 让你费神了, 谢谢大牛

**Comment by lincf0912** [comment]
还是建议你升级。iOS13也有卡死的bug。新版本较为稳定。

发自我的 iPhone

**Comment by 2-Y** [comment]
iphone5 ios10，titleView与backItem也重叠了

**Comment by lincf0912** [comment]
更新[版本1.6.9.4](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.6.9.4)

**Comment by 2-Y** [comment]
确实，同事的库版本是1.6.8，我的事1.6.9
