### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by jun-hui** [lincf0912/LFImagePickerController#8]
你好，我用pod导入的，pod搜索出来的只有LFImagePicker，下载下来后，没有LFImagePickerController文件，使用LFImagePickerViewController运行出来也和demo不一样，而且选取照片后完成度始终完成不了100%，一直等待状态，也进行不了其他操作，望指点，谢谢

**Comment by lincf0912** [comment]
建议使用pod导入，直接在Podfile加上 pod 'LFImagePickerController' 即可

**Comment by jun-hui** [comment]
导不进去，会报错，大致是说找不到‘LFImagePickerController’库。另外，点击查看不是从相册选取的照片如何修改，我用的如下方法：
![a32e08b2-e309-48b1-9436-70d0eed5c3e4](https://cloud.githubusercontent.com/assets/23160552/26713786/ea46e202-47a0-11e7-958a-babb4a97cdd0.png)
（不添加 imagePicker.selectedAssets = self.imagesArray;的话，得到的photos永远只有一个）
但是有个问题，编辑后的图片下边不会更新，且点击即崩溃：
![2f449d43-05a4-4727-824c-f422da95385f](https://cloud.githubusercontent.com/assets/23160552/26713851/34ea8e30-47a1-11e7-9a70-3353ff08d549.png)

**Comment by lincf0912** [comment]
1、pod setup 之后再试试能不能pod search LFImagePickerController
2、imagePicker.selectedAssets = self.imagesArray;这句是代表全选而已，没有的话就没有选中。
photos是选中的回调结果，你选择n张，photos.count=n；
我在demo上测试没有你说的问题（**编辑后的图片下边不会更新，且点击即崩溃**）
你这个展示方式在demo呈现是 **预览模式（image对象）**你可以看看

**Comment by jun-hui** [comment]
嗯，看到了，是要编辑之后才会出现在photos里面，但是查看时候不编辑，点完成之后photos永远都会返回一个，返回的是查看的最后一张图片。可否留个联系方式呢，还有些疑问，我Q：515044778

**Comment by jun-hui** [comment]
更新 cocoapods 之后仍然无法找到 LFImagePickerController 库：
![28cfb45d-d1d8-4339-9602-1215529a2f28](https://cloud.githubusercontent.com/assets/23160552/26718303/238e1d0c-47b3-11e7-81cf-bc855a3b49c9.png)

**Comment by lincf0912** [comment]
UI右上角 选择，你应该是没打勾；编辑完默认是选中

**Comment by lincf0912** [comment]
Release 1.1.9 ：修复崩溃问题
