### ISSUE TITLE
icloud图片会出现无法显示,黑屏

### ISSUE THREAD

**Issue by 2-Y** [lincf0912/LFImagePickerController#80]
手机有一部分图片原图存放在icloud，而手机相册中只有缩略图，然后这种情况在列表中会显示，点击后放大预览就无法显示图片，黑屏

**Comment by lincf0912** [comment]
它可能是下载失败。这里缺乏了一些提示信息。请问如果在黑屏的情况下勾选并发送。可以获取到图片吗？

发自我的 iPhone

**Comment by 2-Y** [comment]
是同事手机，并没有太注意是否能拿到原图，微信是能正常显示原图的，明日我再详细测试一下

**Comment by lincf0912** [comment]
如果微信可以那就表示没问题了。这个bug我会详细测试它。感谢你的反馈。

发自我的 iPhone

**Comment by lincf0912** [comment]
[版本1.6.9.6](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.6.9.6)
