### ISSUE TITLE
Use of undeclared identifier 'LFAssetSubMediaTypePhotoPiiic'; did you mean 'LFAssetMediaTypePhoto'?

### ISSUE THREAD

**Issue by zinwalin** [lincf0912/LFImagePickerController#83]
![image](https://user-images.githubusercontent.com/5416196/79418161-7af05d80-7fe6-11ea-933e-49637a716a24.png)

**Comment by lincf0912** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/10151410/79418792-0ae2d700-7fe8-11ea-8660-c74451d44d99.png">
