### ISSUE TITLE
正常模式,标清图变形了

### ISSUE THREAD

**Issue by anselPeng** [lincf0912/LFImagePickerController#84]
正常模式,选中图片后,首页显示图片变形了

**Comment by lincf0912** [comment]
发图看看

发自我的iPhone

**Comment by anselPeng** [comment]
感谢回复,这边发不了图,图我发你在github上留的qq邮箱了

**Comment by lincf0912** [comment]
更新[版本1.7.1.1](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.7.1.1)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/10151410/79854034-669fcc80-83fb-11ea-8de1-5fa0d8f2d6c4.png">
