### ISSUE TITLE
设定最长30秒视频，拖动时有时会出错，变成超过30秒。

### ISSUE THREAD

**Issue by zinwalin** [lincf0912/LFImagePickerController#85]
[操作视频链接](https://youtu.be/OXCDEeersCE)

**Comment by lincf0912** [comment]
感谢您的反馈。
编辑功能不属于这个框架，下次请提交至[LFMediaEditingController issues](https://github.com/lincf0912/LFMediaEditingController/issues)
请更新[LFMediaEditingController  1.4.5](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.5)
