### ISSUE TITLE
拍照按钮能不能改成拍摄？

### ISSUE THREAD

**Issue by zinwalin** [lincf0912/LFImagePickerController#86]
![image](https://user-images.githubusercontent.com/5416196/81555265-e1388800-93ba-11ea-9365-2c6794625292.png)

视频和照片界面里，按钮都叫“拍照”，　不太合理。能否统一改成“拍摄”。

**Comment by lincf0912** [comment]
拍图片或拍视频会根据设定和当前选择的数量来设置，所以也不一定是拍摄。或许它没有文字可能会清爽点。这些资源都是来自TZImagePickerController项目。

**Comment by zinwalin** [comment]
> 拍图片或拍视频会根据设定和当前选择的数量来设置，所以也不一定是拍摄。或许它没有文字可能会清爽点。这些资源都是来自TZImagePickerController项目。

拍摄其实包含拍照和摄影，一个想法，不一定对。

**Comment by lincf0912** [comment]
它是一张图片。是可以自定义的。`imagePicker.takePictureImageName = @"xxx.png"`
@"xxx.png" 需要放到Assets.xcassets内
