### ISSUE TITLE
有办法取得所选图片或视频的长度和宽度吗？　

### ISSUE THREAD

**Issue by zinwalin** [lincf0912/LFImagePickerController#87]
![image](https://user-images.githubusercontent.com/5416196/84334139-36d3a080-abc4-11ea-800d-4dac8b25716e.png)

**Comment by lincf0912** [comment]
所以要认真看demo的事例代码。
<img width="400" alt="image" src="https://user-images.githubusercontent.com/10151410/84334615-5ddea200-abc5-11ea-9c02-b8c952a1bf91.png">
