### ISSUE TITLE
原图(FullImage)功能可否隐藏？

### ISSUE THREAD

**Issue by zinwalin** [lincf0912/LFImagePickerController#88]
没找到配置的参数。

**Comment by lincf0912** [comment]
不解析了。
<img width="482" alt="image" src="https://user-images.githubusercontent.com/10151410/84565561-8d93d280-ad9c-11ea-827e-782f240cf021.png">

<img width="687" alt="image" src="https://user-images.githubusercontent.com/10151410/84565570-98e6fe00-ad9c-11ea-85ec-3cf837678082.png">
