### ISSUE TITLE
目前排序功能不生效，请问如何进行修改

### ISSUE THREAD

**Issue by hike2008** [lincf0912/LFImagePickerController#89]

**Comment by lincf0912** [comment]
请提供你的初始化代码。

发自我的iPhone

**Comment by hike2008** [comment]
我查到了，下面这个方法的兼容性问题，导致排序方法失效

![image](https://user-images.githubusercontent.com/8948629/85125737-c29d9a80-b25e-11ea-846c-4a90d14534eb.png)

**Comment by hike2008** [comment]
> 我查到了，下面这个方法的兼容性问题，导致排序方法失效
> 
> ![image](https://user-images.githubusercontent.com/8948629/85125737-c29d9a80-b25e-11ea-846c-4a90d14534eb.png)

修改成初始化的值，排序就正常了；
