### ISSUE TITLE
调用图片编辑功能，内存会暴涨。

### ISSUE THREAD

**Issue by xqzp** [lincf0912/LFImagePickerController#9]
选择图片，进入预览，点击编辑功能，此时内存突然暴涨。编辑完成后又爆降。如果调用相机后，拍摄完图片，再调用预览编辑，内存暴涨导致程序闪退。

**Comment by lincf0912** [comment]
我这边没有出现暴涨的情况，请问你是用什么机型？

**Comment by xqzp** [comment]
6P
原始邮件
发件人:lincf0912notifications@github.com
收件人:lincf0912/LFImagePickerControllerLFImagePickerController@noreply.github.com
抄送:xqzpxiongquan@zhpyx.com; Authorauthor@noreply.github.com
发送时间:2017年6月8日(周四) 13:34
主题:Re: [lincf0912/LFImagePickerController] 调用图片编辑功能，内存会暴涨。 (#9)


我这边没有出现暴涨的情况，请问你是用什么机型？

**Comment by lincf0912** [comment]
麻烦你更新下代码再看看

**Comment by xqzp** [comment]
代码没有更新啊。另外我想在拍摄完成后增加编辑预览 编辑功能，怎么修改啊。

**Comment by lincf0912** [comment]
内存暴涨可能因为要编辑的图片非常大导致。往后更新会优化编辑的性能。
拍摄完成后增加编辑功能暂时不支持，可以关注下LFCameraPickerController往后的更新

**Comment by lincf0912** [comment]
麻烦你更新一下最新版本试试

**Comment by lincf0912** [comment]
顺便说一下，LFCameraPickerController已经加入图片编辑功能了
