### ISSUE TITLE
图片点击预览后, 下拉图片, 退出预览, 就会页面卡死

### ISSUE THREAD

**Issue by SnailLoveSmile** [lincf0912/LFImagePickerController#92]
预览图片左右滑动会有点卡

**Comment by SnailLoveSmile** [comment]
iOS14, iPhoneX

**Comment by SnailLoveSmile** [comment]
项目用的Xcode 12.0编译出的问题

**Comment by lincf0912** [comment]
估计是iOS14的相册API有变动。需要一段时间后才有空更新，估计得正式版之后。拖后腿了。🤦🏻‍♂️

**Comment by SnailLoveSmile** [comment]
嗯嗯

**Comment by lincf0912** [comment]
[版本1.7.3](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.7.3)适配iOS14

**Comment by SnailLoveSmile** [comment]
好嘞. 感谢大神
