### ISSUE TITLE
最新版本相册权限有问题吧

### ISSUE THREAD

**Issue by charlesYun** [lincf0912/LFImagePickerController#93]
一直显示请允许访问相册，实际上权限是正常的

**Comment by charlesYun** [comment]
14.0以后的版本是正常的，测试手机11.4版本不行。

**Comment by lincf0912** [comment]
好的。感谢你的反馈。

**Comment by charlesYun** [comment]
还有一个小问题，右上角那个选择框有点大呢，整体看起来不是很协调，建议参考下微信，调整下大小。


Caoyunxiao


在2020年10月13日 11:09，Lam<notifications@github.com> 写道：

好的。感谢你的反馈。

**Comment by lincf0912** [comment]
[版本1.7.3.1](https://github.com/lincf0912/LFImagePickerController/releases/tag/1.7.3.1)
UI的问题不着急，我稍后再调整。

**Comment by charlesYun** [comment]
导航栏那些相簿列表，为0的应该直接过滤吧，还有建议直接提供一个主题色的选项，不需要一个个设置。


Caoyunxiao


在2020年10月13日 14:09，Lam<notifications@github.com> 写道：

版本1.7.3.1
UI的问题不着急，我稍后再调整。

**Comment by lincf0912** [comment]
个人需求，请fork项目，自行修改。
相簿现在为0，在选择的过程中可以有新的照片或视频出现的。只是你没有这样的需求。
颜色方案也应该是使用框架来准备的，框架即使内置有100套方案也不能满足的。其实每项的设置是源于TZImagePickerController。我认为它的实际作用不大。但比没有会好点。
