### ISSUE TITLE
请问可以直接调用有编辑功能的预览页面吗?

### ISSUE THREAD

**Issue by MiaYY** [lincf0912/LFImagePickerController#94]
![1](https://user-images.githubusercontent.com/19600507/108965213-878a1b80-76b7-11eb-99e5-c26614ddf127.jpeg)
![2](https://user-images.githubusercontent.com/19600507/108965223-8bb63900-76b7-11eb-8aa4-7ec753d841b6.jpeg)

**Comment by MiaYY** [comment]
进入相册，左下角有个预览按钮，能不能直接跳过进入相册这一步，直接进入预览按钮所跳转的页面？

**Comment by lincf0912** [comment]
有对应的初始化方法。
你运行demo看看。

发自我的iPhone

**Comment by MiaYY** [comment]
不是最新版本的代码也有这个功能吗？

**Comment by lincf0912** [comment]
你看一下源码吧。

发自我的iPhone

**Comment by MiaYY** [comment]
好的，谢谢

**Comment by MiaYY** [comment]
已解决
